In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,test_size=0.2)

In [4]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/Users/skakibahammed/code_playground/Machine_Learning/coursera/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [5]:
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9722222222222222

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9694444444444444

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5, shuffle=True)
kf

KFold(n_splits=5, random_state=None, shuffle=True)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index, test_index)

[0 1 3 4 5 7 8] [2 6]
[1 2 4 5 6 7 8] [0 3]
[0 2 3 5 6 7 8] [1 4]
[0 1 2 3 4 6 7] [5 8]
[0 1 2 3 4 5 6 8] [7]


In [9]:
def get_score(model, X_train, y_train, X_test, y_test):
  model.fit(X_train, y_train)
  score = model.score(X_test, y_test)
  return score

In [11]:
from sklearn.model_selection import StratifiedKFold

In [12]:
folds = StratifiedKFold(n_splits=5, shuffle=True)

In [14]:
scores_l = []
scores_s = []
scores_r = []

for train_index, test_index in kf.split(digits.data):
  X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
  scores_l.append(get_score(LogisticRegression(), X_train, y_train, X_test, y_test))
  scores_s.append(get_score(SVC(), X_train, y_train, X_test, y_test))
  scores_r.append(get_score(RandomForestClassifier(), X_train, y_train, X_test, y_test))

/Users/skakibahammed/code_playground/Machine_Learning/coursera/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/skakibahammed/code_playground/Machine_Learning/coursera/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also wan

In [15]:
scores_l

[0.975,
 0.9666666666666667,
 0.9721448467966574,
 0.9805013927576601,
 0.947075208913649]

In [16]:
scores_s

[0.9888888888888889,
 0.9888888888888889,
 0.9888579387186629,
 0.9916434540389972,
 0.9777158774373259]

In [17]:
scores_r

[0.9694444444444444,
 0.9833333333333333,
 0.9860724233983287,
 0.9777158774373259,
 0.958217270194986]

In [18]:
from sklearn.model_selection import cross_val_score

In [19]:
cross_val_score(LogisticRegression(), digits.data, digits.target, cv=5)

/Users/skakibahammed/code_playground/Machine_Learning/coursera/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/skakibahammed/code_playground/Machine_Learning/coursera/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also wan

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [20]:
cross_val_score(SVC(), digits.data, digits.target, cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [21]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=5)

array([0.92777778, 0.92222222, 0.95264624, 0.96935933, 0.91086351])